### ISSUE TITLE
'unitparameter' is an invalid keyword argument for UnitDomainElement

### ISSUE THREAD

**Issue by Anaphory** [clld/clld#100]
I had assumed that the way to specify which `UnitParameter` a `UnitDomainElement` belongs to would be through a keyword argument `unitparameter`. However,

    common.UnitDomainElement(
                …,
                unitparameter=meanings)

throws
```
 Traceback (most recent call last):
  File "…/scripts/initializedb.py", line 437, in <module>
    initializedb(create=main, prime_cache=prime_cache)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\clld-1.8.0-py3.5.egg\clld\scripts\util.py", line 238, in initializedb
    create(args)
  File "plld_app/scripts/initializedb.py", line 124, in main
    add_lexical_data(word_list_files[0], meanings, cognacy_classes, lang)
  File "plld_app/scripts/initializedb.py", line 177, in add_lexical_data
    unitparameter=meanings)
  File "<string>", line 4, in __init__
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\sqlalchemy\orm\state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\sqlalchemy\orm\state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\clld-1.8.0-py3.5.egg\clld\db\meta.py", line 242, in __init__
    super(Base, self).__init__(**kwargs)
  File "C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 649, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'unitparameter' is an invalid keyword argument for UnitDomainElement
```
whereas

    common.UnitDomainElement(
                …,
                parameter=meanings)
does not. (I have not yet got far enough down the line to see whether it does what it needs to do.)

Is this working as intended (how was I supposed to know) or a bug?

**Comment by xrotwang** [comment]
Yeah, it does, see https://github.com/clld/clld/blob/master/clld/db/models/unitparameter.py#L61
The API is a bit inconsistent there.
