### ISSUE TITLE
incompatibility with rdflib 6

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#238]
```python
Traceback (most recent call last):
  File "/usr/venvs/phoible/lib/python3.8/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/usr/venvs/phoible/lib/python3.8/site-packages/mako/template.py", line 478, in render_unicode
    return runtime._render(
  File "/usr/venvs/phoible/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/usr/venvs/phoible/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/venvs/phoible/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/venvs/phoible/lib/python3.8/site-packages/clld/web/templates/resource_rdf.mako", line 16, in render_body
    ${h.rdf.properties_as_xml_snippet(request.resource_url(ctx), ctx.__rdf__(request))|n}
  File "/usr/venvs/phoible/lib/python3.8/site-packages/clld/lib/rdf.py", line 92, in properties_as_xml_snippet
    g.add((subject, p, o))
  File "/usr/venvs/phoible/lib/python3.8/site-packages/rdflib/graph.py", line 411, in add
    assert isinstance(p, Node), "Predicate %s must be an rdflib term" % (p,)
AssertionError: Predicate dcterms:about must be an rdflib term`
```

**Comment by xrotwang** [comment]
Maybe `clld.lib.rdf.expand_predicate` must be more strict (https://github.com/clld/clld/blob/c43e5eaeadc4ac23bd13277ead99dbb695bc0835/src/clld/lib/rdf.py#L56). At least, returning `str` doesn't work anymore.
